CREATE TABLE IF NOT EXISTS users(
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(60) UNIQUE NOT NULL,
    "password" VARCHAR(120) NOT NULL,
    isAdm BOOLEAN NOT NULL
);